blank_issues_enabled: false  
contact_links:
  - name: ðŸ’¬ Ask a Question (Discussions)
    url: https://github.com/limbo666/DesktopFences/discussions
    about: Please ask questions, share ideas, or request help here. Do not open an Issue for these.
